# Generated by Django 5.1.7 on 2025-10-23 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_views', models.IntegerField(default=0, verbose_name='总阅读量')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='唯一访客数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 't_articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=1, verbose_name='阅读次数')),
                ('first_viewed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次阅读时间')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='最后阅读时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='articles.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章阅读记录',
                'verbose_name_plural': '文章阅读记录',
                'db_table': 't_article_view_records',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
